In [1]:
import numpy as np

In [2]:
matriz = np.array([[1,2,3,4,22],[5,6,7,8,25],[9,10,11,12,30],[13,14,15,16,35]])
matriz

array([[ 1,  2,  3,  4, 22],
       [ 5,  6,  7,  8, 25],
       [ 9, 10, 11, 12, 30],
       [13, 14, 15, 16, 35]])

In [6]:
primeira_linha = matriz[1]
segunda_linha = matriz[2]
segunda_coluna = matriz[:,1]
terceira_coluna = matriz[:,2]

print(primeira_linha)
print(segunda_linha)
print(segunda_coluna)
print(terceira_coluna)



[ 5  6  7  8 25]
[ 9 10 11 12 30]
[ 2  6 10 14]
[ 3  7 11 15]
